@IsTest
global with sharing class HousingRegisterControllerTest
{
   /* @IsTest(SeeAllData=true)
    static void testRegistration()
    {
        HousingRegisterController cController = new HousingRegisterController();
        cController.szUsername = 'TestName';
        cController.szEmail = 'test@force.com';
        cController.szAppartment = '1';
        cController.szCity = 'Donetsk';
        cController.szRegion = 'East';
        cController.szStreet = 'Str 1110';
        cController.szFirstName = 'Name';
        cController.szLastName = 'Last';
        System.assertEquals(null, cController.registerUser());
        cController.szPassword = 'abcd1234';
        cController.szConfirmPassword = 'abcd123';
        System.assertEquals(null, cController.registerUser());
        cController.szPassword = 'abcd1234';
        cController.szConfirmPassword = 'abcd1234';
        System.assertNotEquals(null, cController.registerUser());
        cController.szRegion = 'Est';
        System.assertEquals(null, cController.registerUser());
    }
    @IsTest(SeeAllData=true)
    static void testRedirectToLoginRegistration()
    {
        HousingRegisterController cController = new HousingRegisterController();

        System.assertNotEquals(null, cController.redirectToHousingLoginPage());
    }*/

}